name: Stop Instances Experiment

on:
  workflow_dispatch:

jobs:
  stop-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if FIS Experiment Template Exists
        id: check_template
        run: |
          TEMPLATE_ID=$(aws fis list-experiment-templates --query "experimentTemplates[?description=='Experiment to stop EC2 instances'].id" --output text)
          echo Template ID: $TEMPLATE_ID
          echo "template_id=$TEMPLATE_ID" >> $GITHUB_ENV

      - name: Replace placeholders in FIS template
        if: steps.check_template.outputs.template_id == ''
        run: |
          sed -e "s/\${AWS_REGION}/${{ secrets.AWS_REGION }}/g" \
              -e "s/\${AWS_ACCOUNT_ID}/${{ secrets.AWS_ACCOUNT_ID }}/g" \
              -e "s/\${INSTANCE_ID}/${{ secrets.INSTANCE_ID }}/g" \
              -e "s/\${IAM_ROLE}/${{ secrets.IAM_ROLE }}/g" \
              fis-templates/stop-instance-template.json > fis-templates/stop-instances-template-processed.json

      - name: Create FIS Experiment Template for Stop Instances
        if: steps.check_template.outputs.template_id == ''
        run: |
          aws fis create-experiment-template --cli-input-json file://fis-templates/fis-stop-instances-template-processed.json
